language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.4"
  - "5.11"
  - "6.3"
sudo: false
before_install:
  - "npm install"
script:
  - "npm run clean"
  - "npm run lint"
  - "npm run test-travis"
  - "npm run build"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
